version: 1

formatters:
  simple:
    format: "%(asctime)s %(name)s: %(message)s"
  extended:
    format: "[%(asctime)s - %(filename)s:%(lineno)s - %(funcName)20s()] %(levelname)s: %(message)s"

handlers:
  file_handler:
    class: logging.FileHandler
    level: INFO
    filename: building-detection.log
    formatter: extended

loggers:
  file:
    handlers: [file_handler]
root:
  handlers: [file_handler]